# render.yaml
services:
  - type: web
    name: resume-jd-matcher
    env: python
    plan: free
    region: oregon   # or nearest free region
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn app_main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
